---
# handlers file for lighthouse-role
- name: nginx reload
  become: true
  command: nginx -s reload
- name: start nginx
  become: true
  ansible.builtin.service:
    name: nginx
    state: started

